version: "3.9"

services:
  odin:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ../configs:/app/configs
    depends_on:
      - redis

  redis:
    image: redis:latest
