version: "3.9"

services:
  odin:
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../config:/app/config
    depends_on:
      - redis

  redis:
    image: redis:latest
