apiVersion: v1
kind: ConfigMap
metadata:
  name: odin-api-config
data:
  config.yaml: |+
    api:
      server:
        port: 8000
      redis:
        host: odin-redis-master
        port: 6379
        dbname: 0
