api:
  server:
    port: 8000

  redis:
    host: localhost #redis
    port: 6379
    password: ""
    dbname: 0

healthcheck:
  cron:
    timeout: 5
    pattern: "*/5 * * * * *"

  redis:
    host: localhost #redis
    port: 6379
    password: ""
    dbname: 0
