apiVersion: v1
kind: ConfigMap
metadata:
  name: odin-healthcheck-config
data:
  config.yaml: |+
    healthcheck:
      cron:
        timeout: 5
        pattern: "0 * * * * *"
      redis:
        host: odin-redis-master
        port: 6379
        dbname: 0
