apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin-api
  labels:
    app: odin-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odin-api
  template:
    metadata:
      labels:
        app: odin-api
    spec:
      containers:
        - name: odin-api
          image: minm47/odin-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odin-redis
                key: redis-password
      volumes:
        - name: config-volume
          configMap:
            name: odin-api-config
            items:
            - key: config.yaml
              path: config.yaml
