{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "odin.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-api" (include "odin.name" .) }}
    {{- include "odin.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
