apiVersion: v1
kind: Service
metadata:
  name: {{ include "odin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-api" (include "odin.name" .) }}
    {{- include "odin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ printf "%s-api" (include "odin.name" .) }}
    {{- include "odin.selectorLabels" . | nindent 4 }}
